### ISSUE TITLE
Kubectl and kustomization not updated

### ISSUE THREAD

**Issue by edubacco** [sighupio/fury-images#43]
Hi @nutellinoit,
speaking about the [drone-kustomize](https://github.com/sighupio/fury-images/blob/master/drone-kustomize/spec.yaml) image, I've noticed that both kubectl and kustomization are in an old version, it's possible to update it?
Thanks!
Edu

**Comment by nutellinoit** [comment]
Hi @edubacco , updated images with new versions matrix : https://github.com/sighupio/fury-images/blob/master/drone-kustomize/spec.yaml

**Comment by edubacco** [comment]
❤️  @nutellinoit!
